Update regression.yml

diff --git a/.github/workflows/regression.yml b/.github/workflows/regression.yml
--- a/.github/workflows/regression.yml
+++ b/.github/workflows/regression.yml
@@ -46,8 +46,14 @@ jobs:
         run: |
           # Знайдемо файл testops.py
           testops_path=$(find /__w/ -name "testops.py" | head -n 1)
+          if [ -z "$testops_path" ]; then
+            echo "File testops.py not found"
+            exit 1
+          fi
           # Виконаємо Python-скрипт для заміни імпортів
-          python3 .github/workflows/replaceQaseioModel.py $testops_path
+          echo "$testops_path"
+          python3 .github/workflows/replaceQaseioModel.py "$testops_path"
+          
       - run: |
           if [ "${{github.event_name}}" = "schedule" ]; then
             export args="-m regression"
